/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  MoviesRequestBuilderNavigationMetadata,
  MoviesRequestBuilderRequestsMetadata,
  type MoviesRequestBuilder,
} from "./movies/index.js";
// @ts-ignore
import {
  apiClientProxifier,
  ParseNodeFactoryRegistry,
  SerializationWriterFactoryRegistry,
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
  type RequestAdapter,
} from "@microsoft/kiota-abstractions";
// @ts-ignore
import {
  FormParseNodeFactory,
  FormSerializationWriterFactory,
} from "@microsoft/kiota-serialization-form";
// @ts-ignore
import {
  JsonParseNodeFactory,
  JsonSerializationWriterFactory,
} from "@microsoft/kiota-serialization-json";
// @ts-ignore
import { MultipartSerializationWriterFactory } from "@microsoft/kiota-serialization-multipart";
// @ts-ignore
import {
  TextParseNodeFactory,
  TextSerializationWriterFactory,
} from "@microsoft/kiota-serialization-text";

/**
 * Instantiates a new {@link MovieClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createMovieClient(requestAdapter: RequestAdapter) {
  if (requestAdapter === undefined) {
    throw new Error("requestAdapter cannot be undefined");
  }
  const serializationWriterFactory =
    requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
  const parseNodeFactoryRegistry =
    requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
  const backingStoreFactory = requestAdapter.getBackingStoreFactory();

  if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
    parseNodeFactoryRegistry.registerDefaultDeserializer(
      JsonParseNodeFactory,
      backingStoreFactory,
    );
    parseNodeFactoryRegistry.registerDefaultDeserializer(
      TextParseNodeFactory,
      backingStoreFactory,
    );
    parseNodeFactoryRegistry.registerDefaultDeserializer(
      FormParseNodeFactory,
      backingStoreFactory,
    );
  }

  if (serializationWriterFactory.registerDefaultSerializer) {
    serializationWriterFactory.registerDefaultSerializer(
      JsonSerializationWriterFactory,
    );
    serializationWriterFactory.registerDefaultSerializer(
      TextSerializationWriterFactory,
    );
    serializationWriterFactory.registerDefaultSerializer(
      FormSerializationWriterFactory,
    );
    serializationWriterFactory.registerDefaultSerializer(
      MultipartSerializationWriterFactory,
    );
  }

  if (
    requestAdapter.baseUrl === undefined ||
    requestAdapter.baseUrl === null ||
    requestAdapter.baseUrl === ""
  ) {
    requestAdapter.baseUrl =
      import.meta.env.VITE_API_BASE_URL || "http://localhost:3000";
  }
  const pathParameters: Record<string, unknown> = {
    baseurl: requestAdapter.baseUrl,
  };
  return apiClientProxifier<MovieClient>(
    requestAdapter,
    pathParameters,
    MovieClientNavigationMetadata,
    undefined,
  );
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface MovieClient extends BaseRequestBuilder<MovieClient> {
  /**
   * The movies property
   */
  get movies(): MoviesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MovieClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MovieClientNavigationMetadata: Record<
  Exclude<keyof MovieClient, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  movies: {
    requestsMetadata: MoviesRequestBuilderRequestsMetadata,
    navigationMetadata: MoviesRequestBuilderNavigationMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
