/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMovieStatsFromDiscriminatorValue, type MovieStats } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /movies/stats
 */
export interface StatsRequestBuilder extends BaseRequestBuilder<StatsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MovieStats>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MovieStats | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StatsRequestBuilderUriTemplate = "{+baseurl}/movies/stats";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMovieStatsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
