/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AuthResponse extends AdditionalDataHolder, Parsable {
    /**
     * The token property
     */
    token?: string | null;
    /**
     * The user property
     */
    user?: User | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthResponse}
 */
// @ts-ignore
export function createAuthResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse}
 */
// @ts-ignore
export function createErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginUserRequest}
 */
// @ts-ignore
export function createLoginUserRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginUserRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MessageResponse}
 */
// @ts-ignore
export function createMessageResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMessageResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieCollectionResponse}
 */
// @ts-ignore
export function createMovieCollectionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieCollectionResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieCreate}
 */
// @ts-ignore
export function createMovieCreateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieCreate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Movie}
 */
// @ts-ignore
export function createMovieFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovie;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieStats}
 */
// @ts-ignore
export function createMovieStatsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieStats;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieUpdate}
 */
// @ts-ignore
export function createMovieUpdateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieUpdate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieWithDetails_externalData}
 */
// @ts-ignore
export function createMovieWithDetails_externalDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieWithDetails_externalData;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieWithDetails}
 */
// @ts-ignore
export function createMovieWithDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieWithDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterUserRequest}
 */
// @ts-ignore
export function createRegisterUserRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterUserRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ReviewCollectionResponse}
 */
// @ts-ignore
export function createReviewCollectionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoReviewCollectionResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ReviewCreate}
 */
// @ts-ignore
export function createReviewCreateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoReviewCreate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Review}
 */
// @ts-ignore
export function createReviewFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoReview;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserCollectionResponse}
 */
// @ts-ignore
export function createUserCollectionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserCollectionResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {User}
 */
// @ts-ignore
export function createUserFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUser;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WatchlistCollectionResponse}
 */
// @ts-ignore
export function createWatchlistCollectionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWatchlistCollectionResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WatchlistCreate}
 */
// @ts-ignore
export function createWatchlistCreateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWatchlistCreate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WatchlistItem}
 */
// @ts-ignore
export function createWatchlistItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWatchlistItem;
}
/**
 * The deserialization information for the current model
 * @param AuthResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthResponse(authResponse: Partial<AuthResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "token": n => { authResponse.token = n.getStringValue(); },
        "user": n => { authResponse.user = n.getObjectValue<User>(createUserFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse(errorResponse: Partial<ErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { errorResponse.errorEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginUserRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginUserRequest(loginUserRequest: Partial<LoginUserRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginUserRequest.email = n.getStringValue(); },
        "password": n => { loginUserRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MessageResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMessageResponse(messageResponse: Partial<MessageResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { messageResponse.message = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Movie The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovie(movie: Partial<Movie> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "director": n => { movie.director = n.getStringValue(); },
        "genre": n => { movie.genre = n.getStringValue(); },
        "id": n => { movie.id = n.getGuidValue(); },
        "rating": n => { movie.rating = n.getNumberValue(); },
        "releaseYear": n => { movie.releaseYear = n.getNumberValue(); },
        "title": n => { movie.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieCollectionResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieCollectionResponse(movieCollectionResponse: Partial<MovieCollectionResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { movieCollectionResponse.value = n.getCollectionOfObjectValues<MovieWithDetails>(createMovieWithDetailsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieCreate The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieCreate(movieCreate: Partial<MovieCreate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "director": n => { movieCreate.director = n.getStringValue(); },
        "genre": n => { movieCreate.genre = n.getStringValue(); },
        "rating": n => { movieCreate.rating = n.getNumberValue(); },
        "releaseYear": n => { movieCreate.releaseYear = n.getNumberValue(); },
        "title": n => { movieCreate.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieStats The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieStats(movieStats: Partial<MovieStats> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "averageRating": n => { movieStats.averageRating = n.getNumberValue(); },
        "totalMovies": n => { movieStats.totalMovies = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieUpdate The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieUpdate(movieUpdate: Partial<MovieUpdate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "director": n => { movieUpdate.director = n.getStringValue(); },
        "genre": n => { movieUpdate.genre = n.getStringValue(); },
        "rating": n => { movieUpdate.rating = n.getNumberValue(); },
        "releaseYear": n => { movieUpdate.releaseYear = n.getNumberValue(); },
        "title": n => { movieUpdate.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieWithDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieWithDetails(movieWithDetails: Partial<MovieWithDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoMovie(movieWithDetails),
        "externalData": n => { movieWithDetails.externalData = n.getObjectValue<MovieWithDetails_externalData>(createMovieWithDetails_externalDataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieWithDetails_externalData The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieWithDetails_externalData(movieWithDetails_externalData: Partial<MovieWithDetails_externalData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterUserRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterUserRequest(registerUserRequest: Partial<RegisterUserRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { registerUserRequest.email = n.getStringValue(); },
        "name": n => { registerUserRequest.name = n.getStringValue(); },
        "password": n => { registerUserRequest.password = n.getStringValue(); },
        "role": n => { registerUserRequest.role = n.getEnumValue<RegisterUserRequest_role>(RegisterUserRequest_roleObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param Review The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoReview(review: Partial<Review> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "comment": n => { review.comment = n.getStringValue(); },
        "createdAt": n => { review.createdAt = n.getDateValue(); },
        "id": n => { review.id = n.getGuidValue(); },
        "movieId": n => { review.movieId = n.getGuidValue(); },
        "rating": n => { review.rating = n.getNumberValue(); },
        "userId": n => { review.userId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ReviewCollectionResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoReviewCollectionResponse(reviewCollectionResponse: Partial<ReviewCollectionResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { reviewCollectionResponse.value = n.getCollectionOfObjectValues<Review>(createReviewFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ReviewCreate The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoReviewCreate(reviewCreate: Partial<ReviewCreate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "comment": n => { reviewCreate.comment = n.getStringValue(); },
        "movieId": n => { reviewCreate.movieId = n.getGuidValue(); },
        "rating": n => { reviewCreate.rating = n.getNumberValue(); },
        "userId": n => { reviewCreate.userId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param User The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUser(user: Partial<User> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { user.createdAt = n.getDateValue(); },
        "email": n => { user.email = n.getStringValue(); },
        "id": n => { user.id = n.getGuidValue(); },
        "name": n => { user.name = n.getStringValue(); },
        "role": n => { user.role = n.getEnumValue<User_role>(User_roleObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserCollectionResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserCollectionResponse(userCollectionResponse: Partial<UserCollectionResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { userCollectionResponse.value = n.getCollectionOfObjectValues<User>(createUserFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WatchlistCollectionResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWatchlistCollectionResponse(watchlistCollectionResponse: Partial<WatchlistCollectionResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { watchlistCollectionResponse.value = n.getCollectionOfObjectValues<WatchlistItem>(createWatchlistItemFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WatchlistCreate The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWatchlistCreate(watchlistCreate: Partial<WatchlistCreate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "movieId": n => { watchlistCreate.movieId = n.getGuidValue(); },
        "userId": n => { watchlistCreate.userId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WatchlistItem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWatchlistItem(watchlistItem: Partial<WatchlistItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { watchlistItem.createdAt = n.getDateValue(); },
        "id": n => { watchlistItem.id = n.getGuidValue(); },
        "movieId": n => { watchlistItem.movieId = n.getGuidValue(); },
        "userId": n => { watchlistItem.userId = n.getGuidValue(); },
    }
}
export interface ErrorResponse extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The error property
     */
    errorEscaped?: string | null;
}
export interface LoginUserRequest extends AdditionalDataHolder, Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface MessageResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
}
export interface Movie extends AdditionalDataHolder, Parsable {
    /**
     * The director property
     */
    director?: string | null;
    /**
     * The genre property
     */
    genre?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The releaseYear property
     */
    releaseYear?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface MovieCollectionResponse extends AdditionalDataHolder, Parsable {
    /**
     * The value property
     */
    value?: MovieWithDetails[] | null;
}
export interface MovieCreate extends AdditionalDataHolder, Parsable {
    /**
     * The director property
     */
    director?: string | null;
    /**
     * The genre property
     */
    genre?: string | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The releaseYear property
     */
    releaseYear?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface MovieStats extends AdditionalDataHolder, Parsable {
    /**
     * The averageRating property
     */
    averageRating?: number | null;
    /**
     * The totalMovies property
     */
    totalMovies?: number | null;
}
export interface MovieUpdate extends AdditionalDataHolder, Parsable {
    /**
     * The director property
     */
    director?: string | null;
    /**
     * The genre property
     */
    genre?: string | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The releaseYear property
     */
    releaseYear?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface MovieWithDetails extends Movie, Parsable {
    /**
     * The externalData property
     */
    externalData?: MovieWithDetails_externalData | null;
}
export interface MovieWithDetails_externalData extends AdditionalDataHolder, Parsable {
}
export interface RegisterUserRequest extends AdditionalDataHolder, Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The password property
     */
    password?: string | null;
    /**
     * The role property
     */
    role?: RegisterUserRequest_role | null;
}
export type RegisterUserRequest_role = (typeof RegisterUserRequest_roleObject)[keyof typeof RegisterUserRequest_roleObject];
export interface Review extends AdditionalDataHolder, Parsable {
    /**
     * The comment property
     */
    comment?: string | null;
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The movieId property
     */
    movieId?: Guid | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The userId property
     */
    userId?: Guid | null;
}
export interface ReviewCollectionResponse extends AdditionalDataHolder, Parsable {
    /**
     * The value property
     */
    value?: Review[] | null;
}
export interface ReviewCreate extends AdditionalDataHolder, Parsable {
    /**
     * The comment property
     */
    comment?: string | null;
    /**
     * The movieId property
     */
    movieId?: Guid | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The userId property
     */
    userId?: Guid | null;
}
/**
 * Serializes information the current object
 * @param AuthResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthResponse(writer: SerializationWriter, authResponse: Partial<AuthResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("token", authResponse.token);
    writer.writeObjectValue<User>("user", authResponse.user, serializeUser);
    writer.writeAdditionalData(authResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse(writer: SerializationWriter, errorResponse: Partial<ErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("error", errorResponse.errorEscaped);
    writer.writeAdditionalData(errorResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginUserRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginUserRequest(writer: SerializationWriter, loginUserRequest: Partial<LoginUserRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginUserRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", loginUserRequest.email);
    writer.writeStringValue("password", loginUserRequest.password);
    writer.writeAdditionalData(loginUserRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MessageResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMessageResponse(writer: SerializationWriter, messageResponse: Partial<MessageResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!messageResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", messageResponse.message);
    writer.writeAdditionalData(messageResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Movie The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovie(writer: SerializationWriter, movie: Partial<Movie> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movie || isSerializingDerivedType) { return; }
    writer.writeStringValue("director", movie.director);
    writer.writeStringValue("genre", movie.genre);
    writer.writeGuidValue("id", movie.id);
    writer.writeNumberValue("rating", movie.rating);
    writer.writeNumberValue("releaseYear", movie.releaseYear);
    writer.writeStringValue("title", movie.title);
    writer.writeAdditionalData(movie.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieCollectionResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieCollectionResponse(writer: SerializationWriter, movieCollectionResponse: Partial<MovieCollectionResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieCollectionResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<MovieWithDetails>("value", movieCollectionResponse.value, serializeMovieWithDetails);
    writer.writeAdditionalData(movieCollectionResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieCreate The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieCreate(writer: SerializationWriter, movieCreate: Partial<MovieCreate> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieCreate || isSerializingDerivedType) { return; }
    writer.writeStringValue("director", movieCreate.director);
    writer.writeStringValue("genre", movieCreate.genre);
    writer.writeNumberValue("rating", movieCreate.rating);
    writer.writeNumberValue("releaseYear", movieCreate.releaseYear);
    writer.writeStringValue("title", movieCreate.title);
    writer.writeAdditionalData(movieCreate.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieStats The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieStats(writer: SerializationWriter, movieStats: Partial<MovieStats> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieStats || isSerializingDerivedType) { return; }
    writer.writeNumberValue("averageRating", movieStats.averageRating);
    writer.writeNumberValue("totalMovies", movieStats.totalMovies);
    writer.writeAdditionalData(movieStats.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieUpdate The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieUpdate(writer: SerializationWriter, movieUpdate: Partial<MovieUpdate> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieUpdate || isSerializingDerivedType) { return; }
    writer.writeStringValue("director", movieUpdate.director);
    writer.writeStringValue("genre", movieUpdate.genre);
    writer.writeNumberValue("rating", movieUpdate.rating);
    writer.writeNumberValue("releaseYear", movieUpdate.releaseYear);
    writer.writeStringValue("title", movieUpdate.title);
    writer.writeAdditionalData(movieUpdate.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieWithDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieWithDetails(writer: SerializationWriter, movieWithDetails: Partial<MovieWithDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieWithDetails || isSerializingDerivedType) { return; }
    serializeMovie(writer, movieWithDetails, isSerializingDerivedType)
    writer.writeObjectValue<MovieWithDetails_externalData>("externalData", movieWithDetails.externalData, serializeMovieWithDetails_externalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieWithDetails_externalData The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieWithDetails_externalData(writer: SerializationWriter, movieWithDetails_externalData: Partial<MovieWithDetails_externalData> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieWithDetails_externalData || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(movieWithDetails_externalData.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterUserRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterUserRequest(writer: SerializationWriter, registerUserRequest: Partial<RegisterUserRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerUserRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", registerUserRequest.email);
    writer.writeStringValue("name", registerUserRequest.name);
    writer.writeStringValue("password", registerUserRequest.password);
    writer.writeEnumValue<RegisterUserRequest_role>("role", registerUserRequest.role);
    writer.writeAdditionalData(registerUserRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Review The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeReview(writer: SerializationWriter, review: Partial<Review> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!review || isSerializingDerivedType) { return; }
    writer.writeStringValue("comment", review.comment);
    writer.writeDateValue("createdAt", review.createdAt);
    writer.writeGuidValue("id", review.id);
    writer.writeGuidValue("movieId", review.movieId);
    writer.writeNumberValue("rating", review.rating);
    writer.writeGuidValue("userId", review.userId);
    writer.writeAdditionalData(review.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ReviewCollectionResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeReviewCollectionResponse(writer: SerializationWriter, reviewCollectionResponse: Partial<ReviewCollectionResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!reviewCollectionResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Review>("value", reviewCollectionResponse.value, serializeReview);
    writer.writeAdditionalData(reviewCollectionResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ReviewCreate The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeReviewCreate(writer: SerializationWriter, reviewCreate: Partial<ReviewCreate> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!reviewCreate || isSerializingDerivedType) { return; }
    writer.writeStringValue("comment", reviewCreate.comment);
    writer.writeGuidValue("movieId", reviewCreate.movieId);
    writer.writeNumberValue("rating", reviewCreate.rating);
    writer.writeGuidValue("userId", reviewCreate.userId);
    writer.writeAdditionalData(reviewCreate.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param User The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUser(writer: SerializationWriter, user: Partial<User> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!user || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", user.createdAt);
    writer.writeStringValue("email", user.email);
    writer.writeGuidValue("id", user.id);
    writer.writeStringValue("name", user.name);
    writer.writeEnumValue<User_role>("role", user.role);
    writer.writeAdditionalData(user.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserCollectionResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserCollectionResponse(writer: SerializationWriter, userCollectionResponse: Partial<UserCollectionResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userCollectionResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<User>("value", userCollectionResponse.value, serializeUser);
    writer.writeAdditionalData(userCollectionResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WatchlistCollectionResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWatchlistCollectionResponse(writer: SerializationWriter, watchlistCollectionResponse: Partial<WatchlistCollectionResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!watchlistCollectionResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<WatchlistItem>("value", watchlistCollectionResponse.value, serializeWatchlistItem);
    writer.writeAdditionalData(watchlistCollectionResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WatchlistCreate The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWatchlistCreate(writer: SerializationWriter, watchlistCreate: Partial<WatchlistCreate> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!watchlistCreate || isSerializingDerivedType) { return; }
    writer.writeGuidValue("movieId", watchlistCreate.movieId);
    writer.writeGuidValue("userId", watchlistCreate.userId);
    writer.writeAdditionalData(watchlistCreate.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WatchlistItem The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWatchlistItem(writer: SerializationWriter, watchlistItem: Partial<WatchlistItem> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!watchlistItem || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", watchlistItem.createdAt);
    writer.writeGuidValue("id", watchlistItem.id);
    writer.writeGuidValue("movieId", watchlistItem.movieId);
    writer.writeGuidValue("userId", watchlistItem.userId);
    writer.writeAdditionalData(watchlistItem.additionalData);
}
export interface User extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The role property
     */
    role?: User_role | null;
}
export type User_role = (typeof User_roleObject)[keyof typeof User_roleObject];
export interface UserCollectionResponse extends AdditionalDataHolder, Parsable {
    /**
     * The value property
     */
    value?: User[] | null;
}
export interface WatchlistCollectionResponse extends AdditionalDataHolder, Parsable {
    /**
     * The value property
     */
    value?: WatchlistItem[] | null;
}
export interface WatchlistCreate extends AdditionalDataHolder, Parsable {
    /**
     * The movieId property
     */
    movieId?: Guid | null;
    /**
     * The userId property
     */
    userId?: Guid | null;
}
export interface WatchlistItem extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The movieId property
     */
    movieId?: Guid | null;
    /**
     * The userId property
     */
    userId?: Guid | null;
}
export const RegisterUserRequest_roleObject = {
    User: "user",
    Admin: "admin",
} as const;
export const User_roleObject = {
    User: "user",
    Admin: "admin",
} as const;
/* tslint:enable */
/* eslint-enable */
