/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieCollectionWithNextLink}
 */
// @ts-ignore
export function createMovieCollectionWithNextLinkFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieCollectionWithNextLink;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieCreate}
 */
// @ts-ignore
export function createMovieCreateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieCreate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Movie}
 */
// @ts-ignore
export function createMovieFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovie;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MovieUpdate}
 */
// @ts-ignore
export function createMovieUpdateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMovieUpdate;
}
/**
 * The deserialization information for the current model
 * @param Movie The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovie(movie: Partial<Movie> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "director": n => { movie.director = n.getStringValue() ?? null; },
        "genre": n => { movie.genre = n.getStringValue() ?? null; },
        "id": n => { movie.id = n.getStringValue() ?? null; },
        "rating": n => { movie.rating = n.getNumberValue() ?? null; },
        "releaseYear": n => { movie.releaseYear = n.getNumberValue() ?? null; },
        "title": n => { movie.title = n.getStringValue() ?? null; },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieCollectionWithNextLink The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieCollectionWithNextLink(movieCollectionWithNextLink: Partial<MovieCollectionWithNextLink> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "nextLink": n => { movieCollectionWithNextLink.nextLink = n.getStringValue() ?? null; },
        "value": n => { movieCollectionWithNextLink.value = n.getCollectionOfObjectValues<Movie>(createMovieFromDiscriminatorValue) ?? null; },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieCreate The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieCreate(movieCreate: Partial<MovieCreate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "director": n => { movieCreate.director = n.getStringValue() ?? null; },
        "genre": n => { movieCreate.genre = n.getStringValue() ?? null; },
        "rating": n => { movieCreate.rating = n.getNumberValue() ?? null; },
        "releaseYear": n => { movieCreate.releaseYear = n.getNumberValue() ?? null; },
        "title": n => { movieCreate.title = n.getStringValue() ?? null; },
    }
}
/**
 * The deserialization information for the current model
 * @param MovieUpdate The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMovieUpdate(movieUpdate: Partial<MovieUpdate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "director": n => { movieUpdate.director = n.getStringValue() ?? null; },
        "genre": n => { movieUpdate.genre = n.getStringValue() ?? null; },
        "rating": n => { movieUpdate.rating = n.getNumberValue() ?? null; },
        "releaseYear": n => { movieUpdate.releaseYear = n.getNumberValue() ?? null; },
        "title": n => { movieUpdate.title = n.getStringValue() ?? null; },
    }
}
export interface Movie extends AdditionalDataHolder, Parsable {
    /**
     * The director property
     */
    director?: string | null;
    /**
     * The genre property
     */
    genre?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The releaseYear property
     */
    releaseYear?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface MovieCollectionWithNextLink extends AdditionalDataHolder, Parsable {
    /**
     * The nextLink property
     */
    nextLink?: string | null;
    /**
     * The value property
     */
    value?: Movie[] | null;
}
export interface MovieCreate extends AdditionalDataHolder, Parsable {
    /**
     * The director property
     */
    director?: string | null;
    /**
     * The genre property
     */
    genre?: string | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The releaseYear property
     */
    releaseYear?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface MovieUpdate extends AdditionalDataHolder, Parsable {
    /**
     * The director property
     */
    director?: string | null;
    /**
     * The genre property
     */
    genre?: string | null;
    /**
     * The rating property
     */
    rating?: number | null;
    /**
     * The releaseYear property
     */
    releaseYear?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Movie The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovie(writer: SerializationWriter, movie: Partial<Movie> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movie || isSerializingDerivedType) { return; }
    writer.writeStringValue("director", movie.director);
    writer.writeStringValue("genre", movie.genre);
    writer.writeStringValue("id", movie.id);
    writer.writeNumberValue("rating", movie.rating);
    writer.writeNumberValue("releaseYear", movie.releaseYear);
    writer.writeStringValue("title", movie.title);
    writer.writeAdditionalData(movie.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieCollectionWithNextLink The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieCollectionWithNextLink(writer: SerializationWriter, movieCollectionWithNextLink: Partial<MovieCollectionWithNextLink> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieCollectionWithNextLink || isSerializingDerivedType) { return; }
    writer.writeStringValue("nextLink", movieCollectionWithNextLink.nextLink);
    writer.writeCollectionOfObjectValues<Movie>("value", movieCollectionWithNextLink.value, serializeMovie);
    writer.writeAdditionalData(movieCollectionWithNextLink.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieCreate The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieCreate(writer: SerializationWriter, movieCreate: Partial<MovieCreate> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieCreate || isSerializingDerivedType) { return; }
    writer.writeStringValue("director", movieCreate.director);
    writer.writeStringValue("genre", movieCreate.genre);
    writer.writeNumberValue("rating", movieCreate.rating);
    writer.writeNumberValue("releaseYear", movieCreate.releaseYear);
    writer.writeStringValue("title", movieCreate.title);
    writer.writeAdditionalData(movieCreate.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MovieUpdate The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMovieUpdate(writer: SerializationWriter, movieUpdate: Partial<MovieUpdate> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!movieUpdate || isSerializingDerivedType) { return; }
    writer.writeStringValue("director", movieUpdate.director);
    writer.writeStringValue("genre", movieUpdate.genre);
    writer.writeNumberValue("rating", movieUpdate.rating);
    writer.writeNumberValue("releaseYear", movieUpdate.releaseYear);
    writer.writeStringValue("title", movieUpdate.title);
    writer.writeAdditionalData(movieUpdate.additionalData);
}
/* tslint:enable */
/* eslint-enable */
