/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  createMovieFromDiscriminatorValue,
  // serializeMovie,
  serializeMovieUpdate,
  type Movie,
  type MovieUpdate,
} from "../../models/index.js";
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  // type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MoviesDeleteResponse}
 */
// @ts-ignore
export function createMoviesDeleteResponseFromDiscriminatorValue(): (
// parseNode: ParseNode | undefined,
  instance?: Parsable,
) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMoviesDeleteResponse;
}
/**
 * The deserialization information for the current model
 * @param MoviesDeleteResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMoviesDeleteResponse(
  moviesDeleteResponse: Partial<MoviesDeleteResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    message: (n) => {
      moviesDeleteResponse.message = n.getStringValue() ?? null;
    },
  };
}
export interface MoviesDeleteResponse extends AdditionalDataHolder, Parsable {
  /**
   * The message property
   */
  message?: string | null;
}
/**
 * Builds and executes requests for operations under /movies/{id}
 */
export interface MoviesItemRequestBuilder extends BaseRequestBuilder<MoviesItemRequestBuilder> {
  /**
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<MoviesDeleteResponse>}
   */
  delete(
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): Promise<MoviesDeleteResponse | undefined>;
  /**
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<Movie>}
   */
  get(
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): Promise<Movie | undefined>;
  /**
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<Movie>}
   */
  patch(
    body: MovieUpdate,
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): Promise<Movie | undefined>;
  /**
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toDeleteRequestInformation(
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): RequestInformation;
  /**
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): RequestInformation;
  /**
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toPatchRequestInformation(
    body: MovieUpdate,
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MoviesDeleteResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMoviesDeleteResponse(
  writer: SerializationWriter,
  moviesDeleteResponse: Partial<MoviesDeleteResponse> | undefined | null = {},
  isSerializingDerivedType: boolean = false,
): void {
  if (!moviesDeleteResponse || isSerializingDerivedType) {
    return;
  }
  writer.writeStringValue("message", moviesDeleteResponse.message);
  writer.writeAdditionalData(moviesDeleteResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const MoviesItemRequestBuilderUriTemplate = "{+baseurl}/movies/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const MoviesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
  delete: {
    uriTemplate: MoviesItemRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createMoviesDeleteResponseFromDiscriminatorValue,
  },
  get: {
    uriTemplate: MoviesItemRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createMovieFromDiscriminatorValue,
  },
  patch: {
    uriTemplate: MoviesItemRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createMovieFromDiscriminatorValue,
    requestBodyContentType: "application/json",
    requestBodySerializer: serializeMovieUpdate,
    requestInformationContentSetMethod: "setContentFromParsable",
  },
};
/* tslint:enable */
/* eslint-enable */
