/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  // type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StatsGetResponse}
 */
// @ts-ignore
export function createStatsGetResponseFromDiscriminatorValue(): (
// parseNode: ParseNode | undefined,
  instance?: Parsable,
) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoStatsGetResponse;
}
/**
 * The deserialization information for the current model
 * @param StatsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStatsGetResponse(
  statsGetResponse: Partial<StatsGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    averageRating: (n) => {
      statsGetResponse.averageRating = n.getNumberValue() ?? null;
    },
    totalMovies: (n) => {
      statsGetResponse.totalMovies = n.getNumberValue() ?? null;
    },
  };
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StatsGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStatsGetResponse(
  writer: SerializationWriter,
  statsGetResponse: Partial<StatsGetResponse> | undefined | null = {},
  isSerializingDerivedType: boolean = false,
): void {
  if (!statsGetResponse || isSerializingDerivedType) {
    return;
  }
  writer.writeNumberValue("averageRating", statsGetResponse.averageRating);
  writer.writeNumberValue("totalMovies", statsGetResponse.totalMovies);
  writer.writeAdditionalData(statsGetResponse.additionalData);
}
export interface StatsGetResponse extends AdditionalDataHolder, Parsable {
  /**
   * The averageRating property
   */
  averageRating?: number | null;
  /**
   * The totalMovies property
   */
  totalMovies?: number | null;
}
/**
 * Builds and executes requests for operations under /movies/stats
 */
export interface StatsRequestBuilder extends BaseRequestBuilder<StatsRequestBuilder> {
  /**
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<StatsGetResponse>}
   */
  get(
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): Promise<StatsGetResponse | undefined>;
  /**
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StatsRequestBuilderUriTemplate = "{+baseurl}/movies/stats";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatsRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: StatsRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createStatsGetResponseFromDiscriminatorValue,
  },
};
/* tslint:enable */
/* eslint-enable */
