/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createWatchlistItemFromDiscriminatorValue, serializeWatchlistCreate, serializeWatchlistItem, type ErrorResponse, type WatchlistCreate, type WatchlistItem } from '../models/index.js';
// @ts-ignore
import { type WatchlistItemRequestBuilder, WatchlistItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /watchlist
 */
export interface WatchlistRequestBuilder extends BaseRequestBuilder<WatchlistRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.watchlist.item collection
     * @param id Unique identifier of the item
     * @returns {WatchlistItemRequestBuilder}
     */
     byId(id: Guid) : WatchlistItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WatchlistItem>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     * @throws {ErrorResponse} error when the service returns a 409 status code
     */
     post(body: WatchlistCreate, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WatchlistItem | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: WatchlistCreate, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WatchlistRequestBuilderUriTemplate = "{+baseurl}/watchlist";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchlistRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchlistRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: WatchlistItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WatchlistRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WatchlistRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWatchlistItemFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWatchlistCreate,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
