/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createMovieCollectionResponseFromDiscriminatorValue, createMovieFromDiscriminatorValue, serializeMovie, serializeMovieCreate, type ErrorResponse, type Movie, type MovieCollectionResponse, type MovieCreate } from '../models/index.js';
// @ts-ignore
import { MoviesItemRequestBuilderNavigationMetadata, MoviesItemRequestBuilderRequestsMetadata, type MoviesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { StatsRequestBuilderRequestsMetadata, type StatsRequestBuilder } from './stats/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /movies
 */
export interface MoviesRequestBuilder extends BaseRequestBuilder<MoviesRequestBuilder> {
    /**
     * The stats property
     */
    get stats(): StatsRequestBuilder;
    /**
     * Gets an item from the ApiSdk.movies.item collection
     * @param id Unique identifier of the item
     * @returns {MoviesItemRequestBuilder}
     */
     byId(id: Guid) : MoviesItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MovieCollectionResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MovieCollectionResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Movie>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     */
     post(body: MovieCreate, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Movie | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MovieCreate, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MoviesRequestBuilderUriTemplate = "{+baseurl}/movies";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MoviesRequestBuilderNavigationMetadata: Record<Exclude<keyof MoviesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: MoviesItemRequestBuilderRequestsMetadata,
        navigationMetadata: MoviesItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    stats: {
        requestsMetadata: StatsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MoviesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MoviesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMovieCollectionResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: MoviesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMovieFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMovieCreate,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
